# Course Introduction

The concepts and techniques in this course are probably the most useful
in engineering. A *signal* is a function of one or more independent
variables conveying information about a physical (or virtual) phenomena.
A *system* may respond to signals to produce other signals, or produce
signals directly.

::: center
FIGURE
:::

This course is about the mathematical models and related techniques for
the design and understanding of systems as signal transformations. We
focus on a broadly useful class of systems, known as *linear,
time-invariant systems*. You will learn about:

-   the representation and analysis of signals as information carrying
    channels

-   and how to analyze and implement linear, time-invariant systems to
    transform those signals.

## Example Signals and Systems

::::: example
Electrical Circuits. This is a Sallen-Key filter, a second-order system
commonly use to select frequencies from a signal:

:::: center
FIGURE
::::

There are two signals we can easily identify, the input signal as the
voltage applied across $x(t)$, and the output voltage measured across
$y(t)$. We build on your circuits course by viewing this circuit as an
implementation of a more abstract linear system. We see how it can be
viewed as a frequency selective filter. We will see how to answer
questions such as: how do we choose the values of the resistors and
capacitors to select the frequencies we are interested in? and how do we
determine what those frequencies are?
:::::

:::: example
Robotic Joint. This is a Linear, Time-Invariant model of a DC motor, a
mixture of electrical and mechanical components.

::: center
FIGURE
:::

How do we convert the motor into a servo for use in a robotic joint?
What are its characteristics (e.g. how fast can it move)?
::::

:::: example
Audio Processing. Suppose you record an interview for a podcast, but
during an important part of the discussion, the HVAC turns on and there
is an annoying noise in the background.

::: center
FIGURE
:::

How could you remove the noise minimizing distortion to the rest of the
audio?
::::

:::: example
Communications. Consider a wireless sensor, that needs to transmit to a
base station, e.g. a wireless mic system.

::: center
FIGURE
:::

How should the signal be processed so it can be transmitted? How should
the received signal be processed?
::::

## Types of Problems

Applications of this material occur in all areas of science and
engineering. When we have a measured output but are unsure what
combination of inputs and system components could have produced it, we
have a *modeling* problem.

::: center
FIGURE
:::

Models are the bedrock of the scientific method and are required to
apply the concepts of this course to engineering problems.

When we know the input and the system description and desire to know the
output we have an *analysis* problem.

::: center
FIGURE
:::

Analysis problems are the kind you have encountered most often already.
For example, given an electrical circuit and an applied voltage or
current, what are the voltages and currents across and through the
various components.

When we know either the input and desired output and seek the system to
perform this transformation,

::: center
FIGURE
:::

or we know the system description and output and desire the input that
would generate the output,

::: center
FIGURE
:::

we have a *design problem*.

This course focuses on modeling and analysis with applications to
electrical circuits and devices for measurement and control of the
physical world and is broadly applicable to all ECE majors. Some
Examples:

-   Controls, Robotics, & Autonomy: LTI systems theory forms the basis
    of perception and control of machines.

-   Communications & Networking: LTI systems theory forms the basis of
    transmission and reception of signals, e.g. AM and FM radio.

-   Machine Learning: LTI systems are often used to pre-process samples
    or to create basis functions to improve learning.

-   Energy & Power Electronic Systems: linear circuits are often modeled
    as LTI systems.

Subsequent courses, e.g. ECE 3704, focus more on analysis and design.

## Learning Objectives

The learning objectives (LOs) for the course are:

1.  Describe a given system using a block-level description and identify
    the input/output signals.

2.  Mathematically model continuous and discrete linear, time-invariant
    systems using differential and difference equations respectively.

3.  Analyze the use of filters and their interpretation in the time and
    frequency domains and implement standard filters in hardware and/or
    software.

4.  Apply computations of the four fundamental Fourier transforms to the
    analysis and design of linear systems.

5.  Communicate solutions to problems and document projects within the
    domain of signals and systems through formal written documents.

These are broken down further into the following topic learning
objectives (TLOs). The TLOs generally map onto one class meeting but are
used extensively in later TLOs.

1.  Course introduction (OW Forward and §1.0)

    1.  Signals as models

    2.  Systems as transformation of signals

    3.  Prerequisites

2.  Continuous-time (CT) signals (OW §1.1 through 1.4 and 2.5): A
    continuous-time (CT) signal is a function of one or more independent
    variables conveying information about a physical phenomena. This
    lecture gives an introduction to continuous-time signals as
    functions. You learn how to characterize such signals in a number of
    ways and are introduced to two very important signals: the unit
    impulse and the complex exponential.

    1.  Continuous-time signals as functions
        $\mathbb{R}\mapsto\mathbb{C}$

    2.  Transformations of time

    3.  Characterizing signals

        1.  periodic/aperiodic

        2.  even/odd

        3.  energy or/nor power

    4.  Impulse function

    5.  Step function

    6.  Complex exponential

3.  Discrete-time (DT) signals (OW §1.1 through 1.4)

    1.  Discrete-time signals as functions $\mathbb{Z}\mapsto\mathbb{C}$

    2.  Transformations of time index

    3.  Characterizing signals

        1.  periodic/aperiodic

        2.  even/odd

        3.  energy or/nor power

    4.  Impulse function

    5.  Step function

    6.  Complex exponential

4.  CT systems as linear constant coefficient differential equations (OW
    §2.4.1)

    1.  LCCDE and their solution (1st and 2nd order)

    2.  impulse response from LCCDE

5.  DT systems as linear constant coefficient difference equations (OW
    §2.4.2)

    1.  LCCDE and their solution (1st and 2nd order)

    2.  impulse response from LCCDE

6.  Linear time invariant CT systems (OW §1.5, 1.6, 2.3)

    1.  Memory

    2.  Invertability

    3.  Causality

    4.  Stability

    5.  Time-invariance

    6.  Linearity

    7.  Define LTI system

7.  Linear time invariant DT systems (OW §1.5, 1.6, 2.3)

    1.  Memory

    2.  Invertability

    3.  Causality

    4.  Stability

    5.  Time-invariance

    6.  Linearity

    7.  Define LTI system

8.  CT convolution (OW §2.2)

    1.  Review CT LTI systems and superposition property

    2.  CT Convolution Integral

    3.  Properties of convolution

        1.  communative

        2.  distributive

        3.  associative

    4.  Determining system response using convolution with impulse
        response

9.  DT convolution (OW §2.1)

    1.  Review DT LTI systems and superposition property

    2.  DT Convolution Sum

    3.  Properties of convolution

        1.  communative

        2.  distributive

        3.  associative

    4.  Determining system response using convolution with impulse
        response

10. CT block diagrams (OW §1.5.2 and 2.4.3)

    1.  blocks represented by impulse response

    2.  series and parallel connections, reductions

    3.  scale, sum, and integrator blocks

    4.  equivalence of LCCDE's and block diagrams

    5.  first-order differential equation as feedback motif

    6.  second-order differential equation as a feedback motif

    7.  implementing a LCCDE using adders, multipliers, and integrators

11. DT block diagrams (OW §1.5.2 and 2.4.3)

    1.  blocks represented by impulse response

    2.  series and parallel connections, reductions

    3.  scale, sum, and unit delay blocks

    4.  equivalence of LCCDE's and block diagrams

    5.  first-order difference equation as feedback motif

    6.  second-order difference equation as a feedback motif

    7.  implementing a LCCDE using adders, multipliers, and delays

12. Eigenfunctions of CT systems (OW §3.2 and 3.8)

    1.  Eigenfunction $e^{st}$

    2.  Transfer Function $H(s)$

    3.  Stability and Frequency Response (FR) $H(j\omega)$

    4.  How this is useful - decomposition of input signal into complex
        exp

    5.  What signals can be decomposed this way, foreshadow Fourier
        Analysis

13. Eigenfunctions of DT systems (OW §3.2 and 3.8)

    1.  Eigenfunction $z^{n}$

    2.  Transfer Function $H(z)$

    3.  Stability and Frequency Response (FR)
        $H\left(e^{j\omega}\right)$

    4.  How this is useful - decomposition of input signal into complex
        exp

    5.  What signals can be decomposed this way, foreshadow Fourier
        Analysis

14. CT Fourier Series representation of signals (OW §3.3 through 3.5)

    1.  review CT periodic functions

    2.  harmonic sums

    3.  derive synthesis equation

    4.  derive analysis equation

    5.  spectrum plots

    6.  define mean-square convergence

    7.  truncated CT FS

    8.  stable LTI system response using CTFS

    9.  example of the impulse train (for sampling theory later)

    10. formal Dirichlet conditions

    11. properties of CT FS

15. DT Fourier Series representation of signals (OW §3.6 and 3.7)

    1.  review DT periodic functions

    2.  harmonic sums

    3.  derive synthesis equation

    4.  derive analysis equation

    5.  spectrum plots

    6.  stable LTI system response using DTFS

    7.  properties of DT FS

16. CT Fourier Transform (OW §4.0 through 4.7)

    1.  derive the CTFT pair from the CTFS

    2.  Dirichlet existence conditions

    3.  CTFT of the CTFS

    4.  Properties of the CT Fourier Transform

        1.  linearity

        2.  time shift

        3.  conjugacy

        4.  integration and differentiation: application to LCCDE
            $\mapsto$ CTFR

        5.  time scaling

        6.  duality

        7.  convolution: stable LTI system response using CTFT

        8.  multiplication/modulation

        9.  application of the properties in combination

17. DT Fourier Transform (OW §5.0 though 5.8)

    1.  derive the DTFT from DTFS

    2.  DTFT of DTFS

    3.  Properties of the DT Fourier Transform

        1.  periodicity

        2.  linearity

        3.  index-shift: application to LCCDE $\mapsto$ DTFR

        4.  frequency shift

        5.  conjugation

        6.  finite difference and accumulation

        7.  interpolation /index expansion

        8.  frequency differentiation

        9.  Parseval's

        10. convolution: stable LTI system response using DTFT

        11. multiplication/modulation

        12. application of the properties in combination

18. CT Frequency Response (OW §6.1, 6.2, 6.5)

    1.  review CTFR as CTFT of impulse response

    2.  review CTFR to/from LCCDE

    3.  review CTFR to/from block diagram

    4.  magnitude-phase representation of the frequency response

    5.  frequency response acting on sinusoids

    6.  Bode plots

        1.  why plot it this way: dB units and log time axis

        2.  how to read them (**not** construct them manually)

        3.  Bode plots in software, e.g. Matlab/Python/Julia

    7.  CTFR of first and second order systems

19. DT Frequency Response (OW §6.1, 6.2, 6.6)

    1.  review DTFR as DTFT of impulse response

    2.  review DTFR to/from LCCDE

    3.  review DTFR to/from block diagram

    4.  magnitude-phase representation of the frequency response

    5.  frequency response acting on sinusoids

    6.  DTFR plots

        1.  periodicity

        2.  dB units

        3.  DTFR plots in software, e.g. Matlab/Python/Julia

    7.  DTFR of first and second order systems

20. Frequency Selective Filters in CT (OW §3.9, 3.10, 6.3, 6.4)

    1.  ideal low-pass

    2.  ideal high-pass

    3.  ideal bandpass

    4.  ideal notch/bandstop

    5.  practical filters

    6.  transformations

    7.  first and second order systems as building blocks

        1.  review LCCDE representation

        2.  review block diagram representation

        3.  review CTFR representation

        4.  CT 1st order RC+buffer

        5.  CT Sallen-key

21. Frequency Selective Filters in DT (OW §3.11, 6.3, 6.4)

    1.  ideal low-pass

    2.  ideal high-pass

    3.  ideal bandpass

    4.  ideal notch/bandstop

    5.  practical filters

    6.  transformations

    7.  first and second order systems as building blocks

        1.  review LCCDE representation

        2.  review block diagram representation

        3.  review DTFR representation

        4.  DT 1st order implementation in code

        5.  DT 2nd order implementation in code

22. The Discrete Fourier Transform

    1.  time window the DTFT to get the DFT

    2.  interpreting the index axis as DT and CT frequency

    3.  zero-padding

    4.  offline or batched filtering using the DFT

    5.  briefly mention fast algorithms to compute the DFT = FFT

23. Sampling (OW §7.1, 7.3, 7.4)

    1.  sampling using the impulse train

    2.  derive the Nyquist rate

    3.  effects of aliasing

    4.  practical ADC (sample and hold, SAR, bit-width)

    5.  designing anti-aliasing filters

24. Reconstruction (OW §7.2)

    1.  reconstruction as removal of images

    2.  reconstruction as interpolation

    3.  practical DAC: R-2R ladder

    4.  designing reconstruction filters

## Graphical Outline

FIGURES