---
title: "Discrete-Time Signals"

diagram:
  engine:
    tikz:
      execpath: pdflatex
      header-includes:
        - '\usepackage{circuitikz,pgfplots}'
---

Recall from the previous chapter that a discrete-time (DT) signal is modeled as a function $f: \mathbb{Z} \rightarrow \mathbb{C}$. We will write these as $x[n]$, $y[n]$, etc. Note $n$ is dimensionless. These are graphically plotted as stem or "lollipop" plots, as demonstrated in Chapter 2.

Since the domain $\mathbb{Z}$ is usually interpreted as a time index, we will still call these {\it time-domain} signals. In the time-domain, when the co-domain is $\mathbb{R}$ we call these real DT signals. Unlike with CT signals there are no physical limitations requiring DT signals to be real, since in discrete hardware, a value at a given index can be a complex number, i.e. just a pair of numbers. However it is computationally advantageous to restrict ourselves to real arithmetic and such signals are often converted to or from CT signals, which do have to be real. For this reason, real DT signals dominate in models.

## Primitive Models

As with CT signals, we mathematically model DT signals by combining elementary/primitive functions, for example:  

* polynomials: $x[n] = n$, $x[n] = n^2$, etc.
* transendental functions: $x[n] = e^n$, $x[n] = \sin(n)$, $x[n] = \cos(n)$, etc.
* piecewise functions, e.g.
  $$
  x[n] = \left\{  \begin{array}{cl}
  f_1[n] & n < 0\\
  f_2[n] & n \geq 0\\
  \end{array}\right.
  $$
