project:
  type: book
  output-dir: docs
  
book:
  title: "Supplementary Notes for ECE 2714: Signals and Systems"
  author: "C.L. Wyatt"
  date: last-modified
  sidebar:
    style: floating
    search: false
  chapters:
    - index.qmd
    - preface.qmd
    - 01-intro.qmd
    - 02-ct-signals.qmd
    - 03-dt-signals.qmd
    - 04-ct-lccde.qmd
    - 05-dt-lccde.qmd
    - 06-ct-lti.qmd
    - references.qmd
  
bibliography: references.bib

filters:
  - diagram

format:
  html:
    html-math-method: mathml
    theme: simplex
    toc: true
    code-fold: true
  pdf:
    pdf-engine: pdflatex
    default-image-extension: pdf
  docx: default
  odt: default
  epub: default



