project:
  type: book
  output-dir: docs
  
book:
  title: "Supplementary Notes for ECE 2714: Signals and Systems"
  author: "C.L. Wyatt"
  date: last-modified
  repo-url: https://github.com/clwyatt/notes-2714
  downloads: [epub]
  navbar:
    title: "Supplementary Notes for ECE 2714: Signals and Systems"
    search: false
  sidebar:
    title: false
    style: floating
    search: false
  chapters:
    - index.qmd
    - preface.qmd
    - 01-intro.qmd
    - 02-ct-signals.qmd
    - 03-dt-signals.qmd
    - 04-ct-lccde.qmd
    - 05-dt-lccde.qmd
    - 06-ct-lti.qmd
    - 07-dt-lti.qmd
    - 08-ct-conv.qmd
    - 09-dt-conv.qmd
    - 10-ct-block.qmd
    - 11-dt-block.qmd
    - 12-ct-tf.qmd
    - 13-dt-tf.qmd
    - 14-ctfs.qmd
    - 15-dtfs.qmd
    - 16-ctft.qmd
    - 17-dtft.qmd
    - 18-ct-fr.qmd
    - 19-dt-fr.qmd
    - 20-ct-filters.qmd
    - 21-dt-filters.qmd
    - 22-dft.qmd
    - 23-sampling.qmd
    - 24-recon.qmd
  appendices:
    - 26-formulas-tables.qmd
    - image-descriptions.qmd
    - references.qmd

format:
  html:
    html-math-method: mathjax
    default-image-extension: svg
    theme: simplex
    css: style.css
    toc: true
    code-fold: true
    highlight-style: a11y-light
  epub: default
  pdf:
    pdf-engine: pdflatex
    default-image-extension: pdf

bibliography: references.bib
