project:
  type: book
  output-dir: docs
  
book:
  title: "Supplementary Notes for ECE 2714: Signals and Systems"
  author: "C.L. Wyatt"
  date: last-modified
  repo-url: https://github.com/clwyatt/notes-2714
  downloads: [pdf, epub]
  navbar:
    title: "Supplementary Notes for ECE 2714: Signals and Systems"
  sidebar:
    title: false
    style: floating
    search: false
  chapters:
    - index.qmd
    - preface.qmd
    - 01-intro.qmd
    - 02-ct-signals.qmd
    - 03-dt-signals.qmd
    - 04-ct-lccde.qmd
    - 05-dt-lccde.qmd
    - 06-ct-lti.qmd
    - references.qmd

format:
  html:
    html-math-method: mathjax
    default-image-extension: svg
    theme: simplex
    css: style.css
    toc: true
    code-fold: true
  epub: default
  pdf:
    pdf-engine: pdflatex
    default-image-extension: pdf

bibliography: references.bib